os:
  - linux

cache:
  directories:
    - src/vendor/libpcre
    - src/vendor/Nim

language: c

addons:
  artifacts:
    paths:
      - ghcs

before_script:
  - set -e

script:
  - cd src
  - make ghcs
  - make test
