os:
  - linux

cache:
  directories:
    - $HOME/Nim
    - $HOME/nimble
    - $HOME/.nimble

language: c

install:
  - ci/setup_nim.sh

before_script:
  - set -e
  - export PATH=$HOME/Nim/bin:$HOME/.nimble/bin:$PATH

script:
  - cd src
  - make ghcs
  - make test
