os:
  - linux

cache:
  directories:
    - src/vendor/libpcre
    - src/vendor/Nim

language: c

addons:
  apt_packages:
    - pandoc
    - upx
  artifacts:
    paths:
      - ghcs
      - ghcs.1

before_script:
  - set -e
  - gem install fpm deb-s3

script:
  - make test
  - make deb
  - deb-s3 upload --bucket ghcs-apt --codename unstable ghcs_1.0_amd64.deb
