os:
  - linux

cache:
  directories:
    - src/vendor/libpcre
    - src/vendor/Nim

language: c

addons:
  apt_packages:
    - pandoc
  artifacts:
    paths:
      - src/ghcs
      - ghcs.1

before_script:
  - set -e

script:
  - cd src
  - make ghcs
  - make test
  - make deb
  - deb-s3 upload --bucket ghcs-apt ghcs-1.0_amd64.deb
  - cd ..
  - pandoc docs/man.md -s -o ghcs.1
