os:
  - linux

language: c

install:
  - |
      git clone https://github.com/nim-lang/Nim.git
      cd Nim
      sh bootstrap.sh
      cd ..
      git clone https://github.com/nim-lang/nimble.git
      
      cd nimble
      git clone -b v0.13.0 --depth 1 https://github.com/nim-lang/nim vendor/nim
      nim c -r src/nimble install
      cd ..


before_script:
  - set -e
  - set -x
  - export PATH=`pwd`/Nim/bin:`pwd`/nimble/bin:$PATH

script:
  - make ghcs
